### ISSUE TITLE
Not loading properly is trailing / missing

### ISSUE THREAD

**Issue by hradhakrishnan** [GoogleCloudPlatform/region-picker#7] opened 2021-10-12 13:50 UTC
getting the following error in the chrome console. The tool doesnt propoerly load up

Access to link element resource at 'https://cloud.google.com/' (redirected from 'https://cloud.withgoogle.com/data/countries.json') from origin 'https://cloud.withgoogle.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by hradhakrishnan** [comment] 2021-11-02 09:15
Hi, i believe this is the url https://cloud.withgoogle.com/region-picker i used

**Comment by steren** [comment] 2021-11-02 15:40
Thanks. the URL is https://cloud.withgoogle.com/region-picker/

I can see if it's possible to also support the one you shared.

Out of curiosity, where did you click on the URL without the trailing `/` ?

**Comment by hradhakrishnan** [comment] 2021-11-08 17:50
Hi, I'm not sure where I picked the URL from. Possibly typed it in. Hope this helps :)

Hari

**Comment by steren** [comment] 2021-11-08 17:51
Thanks, I'll see if I can change the App Engine config to be compatible when the URL is missing the trailing /

**Comment by Deleplace** [comment] 2021-11-29 10:25
Some considerations:
- With a proper slash at https://cloud.withgoogle.com/region-picker/ , all static asset relative paths are implictly rooted at `https://cloud.withgoogle.com/region-picker/` e.g. `images/icons/help_outline_black_24dp.svg` is resolved as https://cloud.withgoogle.com/region-picker/images/icons/help_outline_black_24dp.svg
- Without a trailing slash at https://cloud.withgoogle.com/region-picker , all static asset relative paths are implictly rooted at `https://cloud.withgoogle.com/` e.g. `images/icons/help_outline_black_24dp.svg` is resolved as https://cloud.withgoogle.com/region-picker/images/icons/help_outline_black_24dp.svg , which is incorrect and returns a 302 to https://cloud.google.com/

The App Engine config LGTM, I'm not aware of any special power beyond "at the root of the current app, serve index.html".

However, the app in production lives under https://cloud.withgoogle.com/ which serves the sub-paths `region-picker` and `region-picker/` alike by letting the appropriate App Engine app serve them. This creates confusion about the proper root path of the relative static assets.

Here are a few possible mitigations I can think of:
1. Wherever the "wrong" URL exists in hyperlinks in the wild, change them with the "proper" URL with trailing slash ;
2. Kindly ask the admins of `cloud.withgoogle.com` if they can return a 404 for the "wrong" URL. Not friendly, but much better that the current mostly-broken page ;
3. Kindly ask the admins of `cloud.withgoogle.com` if they can return a 302 for the "wrong" URL, that seamlessly redirects to the proper URL ;
4. Modify all of the relative paths in the app code to include as prefix the virtual folder "/region-picker/" e.g. `background-image: url(images/icons/gleaf_black_24dp.svg);` becomes `background-image: url(/region-picker/images/icons/gleaf_black_24dp.svg);`. The app.yaml is already set up to accommodate this trick. This can only be achieved by making sure that all the internal relative static resource paths do start with the prefix ;
5. Add a JS workaround hack that "checks if `window.location` is missing the trailing slash, if so make a redirect" ;
6. Change all of the relative paths into full absolute paths with production domain name (not great as the app is not self-contained anymore, and local dev becomes awkward).

It seems to me that (3), (4), (5) are actionable and would each be able to fix the problem.

@steren would you like me to try and make a PR for (4) or (5)?

Note that the whole thing is a bit error-prone, and we'll need to test carefully after a redeploy.

**Comment by steren** [comment] 2021-11-29 17:20
Thanks for the suggestions.

1. yes, it'd be good to check for where this URL is incorrect in the wild and send PRs

I think 3. would be best. but not sure what's feasible.

I would prefer the app not to assume it is served under `/region-picker/` in case users want to deploy it somewhere else. So I am against 4.

I suggest to do 5. Feel free to send a PR.

**Comment by Deleplace** [comment] 2021-11-30 11:11
Implemented 5. in PR #8

**Comment by steren** [comment] 2021-11-30 17:26
Thanks. Merged. It should auto-deploy. let's close once we confirm the issue is fixed

**Comment by Deleplace** [comment] 2021-11-30 20:29
This is indeed deployed in prod, and LGTM

**Closed** 2021-11-30 21:13 UTC
